### ISSUE TITLE
Updating the CUDA Linux GPG Repository Key

### ISSUE THREAD

**Issue by falbrechtskirchinger** [nlohmann/json-ci#11]
For your information:
https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/

This breaks the CUDA toolkit installation step. If you aren't in a hurry to update, there's no need to do anything. I'll be proposing a bigger change (depending on how testing goes) after the 3.11.0 release.

**Comment by nlohmann** [comment]
Done in version 2.4.0
